version: '3.7'

services: 

    reactapp:
        container_name: reactapp
        build:
            context: .
            dockerfile: _infra/Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports: 
            - '8000:3000'
        environment:
            - NODE_ENV=development
